### ISSUE TITLE
Suggested improvements for easier usability

### ISSUE THREAD

**Issue by MikkelDA** [GMPavanLab/LENS#1]
Hi
I was introduced to LENS via Kasper Busk Pedersen (one of your co-authers on the paper "On the Automatic Optimization of Lipid Models in the Martini Force Field using SwarmCG")

I tried using it on my Martini 3 systems, but ran into a few obstacles, so i have some suggestions for how to change some of the code to make it more user friendly.

The need to use MDAnalysis universes containing only the exact beads your are trying to analyse can be a bit tedious, thus i am suggesting you apply the following changes:
**perform_search:**
From:
```
def perform_search(XYZ_UNI, COFF, INIT, END, STRIDE, BOX_const=False):
    beads = XYZ_UNI.select_atoms("all")
```
To:
```
def perform_search(XYZ_UNI, COFF, INIT, END, STRIDE, BOX_const=False, atom_sel="all"):
    beads = XYZ_UNI.select_atoms(atom_sel)
```
**perform_search_time:**
From:
```
def perform_search_time(XYZ_UNI, COFF, INIT, END, STRIDE, BOX_const=False):
    beads = XYZ_UNI.select_atoms("all")
```
To:
```
def perform_search_time(XYZ_UNI, COFF, INIT, END, STRIDE, BOX_const=False, atom_sel="all"):
    beads = XYZ_UNI.select_atoms(atom_sel)
```
**get_gofr_all:**
From
```
def get_gofr_all(universe,b, e, s,rcut, bins):
    selection = universe.select_atoms("all")
```
To:
```
def get_gofr_all(universe,b, e, s,rcut, bins, atom_sel="all"):
    selection = universe.select_atoms(atom_sel)
```

This however has the potential to create a problem in the function "perform_search" which relies on the function "add_zeros", wherein too many counts may be added to the X_all list. Thus i also suggest you change the entire "add_zeros" function as follows:
**add_zeros**
From:
```
def add_zeros(X):
    N=len(X)
    X_all = list()
    for x in X:
        x_all = list()
        count = 0
        for atm in x:
            if atm != count:
                while count < atm:
                    x_all.append([count, 0])
                    count+=1
            if atm == count:
                x_all.append([atm, x[atm]])
            count+=1
        while count < N:
            x_all.append([count, 0])
            count+=1

        X_all.append(x_all)
    return X_all
```
To:
```
def add_zeros(X, beads):
    X_all = list()
    for x in X:
        x_all = np.asarray([[ref, 0] for ref in beads.ix])
        for atm in x:
            x_all[np.where(x_all[:] == atm)[0][0]] = [atm, x[atm]]
        X_all.append(x_all)
    return X_all
```
For this change to "add_zeros" to work the call of "add_zeros" in "perform_search" must also be changed as follows:
**perform_search**
From:
`X_all = add_zeros(sort_dict(list_sum_noself, 0))
`
To:
`X_all = add_zeros(sort_dict(list_sum_noself, 0), beads)
`
These changes allow me to use a universe created from a .tpr file and an .xtc file while specifying the only beads i am interested in easily and without problems.

**Comment by Iximiel** [comment]
Hi! Thank you for the suggestions, this is the "paper repo" so the code here is just a first draft, and it is not as optimized as it could be.

If you want to do a LENS analysis you can use SOAPify that is available via `pip install cpctools` (because soapify was already taken) or by following one of the alternative instruction listed in [SOAPify](https://github.com/GMPavanLab/SOAPify).

Some of your suggestion have been already implemented, along with some changes in the names of the functions, the example for the LENS analysis is [here](https://soapify.readthedocs.io/en/latest/LENS.html), you can use directly a MDA universe instead of preprocessing your system with our hdf5er.

I hope this helped, if there are any problem I am here :)

**Comment by MikkelDA** [comment]
Thanks for the response, i will check out SOAPify.
